### ISSUE TITLE
Unused parameter in JetsForHadTau

### ISSUE THREAD

**Issue by aperloff** [TreeMaker/TreeMaker#290]
There seems to be an unused parameter in JetsForHadTau in the doHadTauBkg.py code (https://github.com/TreeMaker/TreeMaker/blob/Run2_2017/TreeMaker/python/doHadTauBkg.py#L108) Is it there for a reason? It's never used in JetsForHadTauProducer.cc.

**Comment by kpedro88** [comment]
probably left over or incorrectly copied from a different module, it can be deleted

**Comment by aperloff** [comment]
Since taus are my next task I'll do it there and then reference the PR here.

**Comment by aperloff** [comment]
This was fixed by #291

**Comment by kpedro88** [comment]
`dohadTauBkg.py` was not modified in that PR...

**Comment by aperloff** [comment]
My bad. Fixed.
