### ISSUE TITLE
EGamma Energy Corrections

### ISSUE THREAD

**Issue by aperloff** [TreeMaker/TreeMaker#352]
We are missing the EGM recommended energy scale corrections to the 2016, 2017 and 2018 data? These should be added to the LeptonProducer.

**Comment by kpedro88** [comment]
It's not clear to me that any non-leptonic SUSY analyses actually use these (or if we should).

**Comment by aperloff** [comment]
I agree, more review is needed. And yes, I know I'm late in commenting.

**Comment by awhitbeck** [comment]
as I mentioned in the meeting, this doesn't effect the Zinv predictions at all.  However, we do want to show a z-peak in our supplementary material, but maybe somethings more hacky can be cobbled together?

**Comment by kpedro88** [comment]
resolved by #365
