### ISSUE TITLE
AK4 jet b-tagger and working points

### ISSUE THREAD

**Issue by fojensen** [TreeMaker/TreeMaker#420]
To whom it may concern:
I am trying to figure out how BTags is counted in the TreeMaker - what working point and what tagger.

a) I guess the most confusing thing for me is that I see a working point of 0.679 listed in the TreeMaker:
https://github.com/TreeMaker/TreeMaker/blob/Run2_2017/Utils/python/btagint_cfi.py#L6
but when I look at the recommendations:
https://twiki.cern.ch/CMS/BtagRecommendation80XReReco
https://twiki.cern.ch//CMS/BtagRecommendation94X
https://twiki.cern.ch/CMS/BtagRecommendation102X
I do not see that working point anywhere.

b) I see the tagger name which is used is "combinedSecondaryVertexBJetTags"
https://github.com/TreeMaker/TreeMaker/blob/Run2_2018_prompt/Utils/python/btagint_cfi.py#L5
I probably don't know how the tagger info is handled in MINIAOD, but I don't see combinedSecondaryVertexBJetTags listed in any of the recommended taggers. Is this some sort of shorthand which TreeMaker/CMSSW knows to use?

**Comment by kpedro88** [comment]
The actual values used are here:
https://github.com/TreeMaker/TreeMaker/blob/7701765cb1b1d9d1c1cb731eb2f90b64420569a3/TreeMaker/python/makeJetVars.py#L121-L143

Some of these will be updated in the next round based on recent recommendations.
