### ISSUE TITLE
PR integration test not triggering a job failure

### ISSUE THREAD

**Issue by aperloff** [TreeMaker/TreeMaker#508]
When a PR triggers the GitHub actions workflow and integration test is performed after the build. This test runs a unit test. However, if the unit test fails, this does not constitute a failure of the action (see https://github.com/TreeMaker/TreeMaker/pull/505/checks?check_run_id=644339683). This should be fixed so that when unitTest.py fails, so does the job.

**Comment by kpedro88** [comment]
Addressed by #606
