### ISSUE TITLE
Remaining Items for UL

### ISSUE THREAD

**Issue by JHiltbrand** [TreeMaker/TreeMaker#584]
### Consolidated list based on commentary from original issue list #571 and ongoing PR #573 concerning updates for UL. ###

- [x] Add filelists for data
Completed in #594
- [x] Add filelists for signal (RPV and Stealth SYY)
- [ ] Update JEC/JER for FastSim, when available.
- [x] Complete data, fastsim, and signal scenarios
- [x] Once available, add latest JEC/JER corrections for the Summer20UL campaign (currently have Summer19UL)
Based on recommendations from JetMET POG, the Summer19UL JECs are good to be used for the 20UL campaign with the difference in jet response ~O(0.1%) [4]
- [x] Update b tag WP for 2016 preVFP (APV) once available (?)
Completed in #594

### Samples and Cross Sections as of 2021/11/15 ###

- [x] QCD HT binned
    mostly complete for 2016, 2017, and 2018
    
- [x] GJets for 2016
    Done in #594

- [x] WJetsToQQ not available yet, will update
    Taken care of in #594

- [x] ST_s-channel_hadronicDecays not available yet, will update
    nothing for any year
    NOTE: stricken from the "master" production and planning list of samples [5], does not appear it will be produced [6]

- [ ] Various diboson with specific final states not available, will update (WWTo1L1Nu2Q, WZTo1L1Nu2Q, WZTo1L3Nu, ZZTo2L2Q)
    WWTo1L1Nu2Q missing for 2016, 2017 (no MiniAODv2 defined)
    WZTo1L1Nu2Q missing for 2016, 2017 (no MiniAODv2 defined)
    WZTo1L3Nu missing for all years (no MiniAODv1 or v2 defined)
    ZZTo2L2Q missing for all years (no MiniAODv1 or v2 defined)
    
- [x] Several TT + XX (TTTT, TTHH, TTTW, TTWH, TTZH, TTTJ) missing, will update
    TTTW missing for 2016 (production almost complete)
    
- [x] tZq for specific final states, not available, will update
    no specific final states, only ll, 4f version
    NOTE: "Master" production and planning spreadsheet [5] makes no mention of non-inclusive samples [6]

- [x] ZJetsToNuNu_Zpt not available, will update
    missing for 2018, two HT bins for 2016, 2017 with `BPSFilter` keyword
    
- [x] ZJetsToNuNu
   somewhat complete for 2016, complete for 2017 and 2018

- [x] TTJets (genMET cut) not available, will update.
    nothing for any year
    NOTE: No mention of these kind of samples in the production and planning "master" spreadsheet [5] nor pdvm webpage [6]
    
- [x] TTJets HT-binned samples not available, will update (pay attention to k factors)
    nothing for any year
    NOTE: The "master" production and planning spreadsheet [5] thus far does not make reference to HT-binned TTJets samples, appears only inclusive sample being produced [6]
    
- [x] TTJets amc@nlo sample is missing for 2016 and 2018
    MiniAODv2 in production, almost completed

- [x] Show QCD Pt as LO in notes
Completed in #594
- [x] TTTo* remove k factors for mtop samples
Completed in #594
- [x] Add reference for xsecs for signal (https://twiki.cern.ch/twiki/bin/view/LHCPhysics/SUSYCrossSections13TeVgluglu, https://twiki.cern.ch/twiki/bin/view/LHCPhysics/SUSYCrossSections#Cross_sections_for_various_subpr)
Completed in #594

- [x] Verify that correction factors [2] for DYJets and WJets xsecs are not needed.
These were needed when the `pdfwgt` was set to `True` in MG 2.4.2---a change compared to previous campaigns. With the release of MG 2.6.5 the setting of `True` was tested again and the previous observations were drastically reduced [3]; however, it was decided to stick with the original setting of `False` as not everything was perfectly understood. So the correction should not be needed.

- [ ] Add some unit tests for data, signal, FastSim, GJets
All but FastSim added in #592 and #594.

### Cross Section Differences in UL ###
It has been found that several processes have non-trivial differences in cross section for UL compared to previous campaigns. Here a compilation of samples and reasoning is provided.

- WJetsToLNu: There are interference terms introduced in the gridpack and `pdfwgt = true/false` [1]
- ZZTo2L2Nu: The mll cut has been lowered from 40 GeV to 4 GeV [1]
- ST_tW_antitop_5f_NoFullyHadronicDecays: A change in CKM values and hdamp settings

[1] https://hypernews.cern.ch/HyperNews/CMS/get/generators/5172

[2] https://twiki.cern.ch/twiki/bin/viewauth/CMS/MCKnownIssues#WJetsToLNu_HT_and_DYJets_HT_LO_M

[3] https://indico.cern.ch/event/855110/contributions/3613939/attachments/1930820/3197907/2019-09-27_vht_265.pdf

[4] https://cms-talk.web.cern.ch/t/recommended-jec-jer-for-summer20ul-and-fastsim/1395/2

[5] https://docs.google.com/spreadsheets/d/1ABl2p2uwr2EfEbolBEVNcKb_fIXigYY9sqCRT8XIi1Q/edit#gid=1318927481

[6] https://pdmv-pages.web.cern.ch/main_bkg_ul/

**Comment by kpedro88** [comment]
The SVJ t-channel cross sections will also need to be cleaned up.

**Comment by JHiltbrand** [comment]
Hello @kpedro88, @aperloff,
(cc @semrat @devinmahon @cmadrid1)

I know you had some developments for core `TreeMaker` code and I see numerous changes have been merged in within the last couple of weeks. I was wondering what the current status is on your side of things for `TreeMaker` being ready for UL ? From our side, I have been adding in some of the remaining background samples and hecking on final recommendation items and have documented them above. It appears that the only remaining items are a few miscellaneous MC samples and their associated cross sections and FastSim items.

Do you think we are in the regime of being able to produce a first sample with the `Run2_UL` branch and then start thinking about some subsequent validation ? What other things should we be thinking about now that we are closer to producing a first sample ?

**Comment by kpedro88** [comment]
The major outstanding technical item is adding better functionality to store jet constituents. But that's only needed for some analyses that want to explore particle-level tagging.

The main procedural item is figuring out which optional flags (reclusterings, etc.) should be enabled for which samples. But there could be a first production without the optional flags for some samples.

**Comment by aperloff** [comment]
1. In terms of adding "filelists for signal," whose signal are we waiting for?
2. I think some more `QCD_HTXtoY` samples have appeared. Not all of the ones we need, but some. The new one's I see are:
```
/QCD_HT50to100_TuneCP5_PSWeights_13TeV-madgraph-pythia8/RunIISummer20UL16MiniAODv2-106X_mcRun2_asymptotic_v17-v1/MINIAODSIM
/QCD_HT300to500_TuneCP5_PSWeights_13TeV-madgraph-pythia8/RunIISummer20UL16MiniAODv2-106X_mcRun2_asymptotic_v17-v1/MINIAODSIM
/QCD_HT500to700_TuneCP5_PSWeights_13TeV-madgraph-pythia8/RunIISummer20UL16MiniAODv2-106X_mcRun2_asymptotic_v17-v1/MINIAODSIM
/QCD_HT700to1000_TuneCP5_PSWeights_13TeV-madgraph-pythia8/RunIISummer20UL16MiniAODv2-106X_mcRun2_asymptotic_v17-v1/MINIAODSIM

/QCD_HT700to1000_TuneCP5_PSWeights_13TeV-madgraph-pythia8/RunIISummer20UL16MiniAODAPVv2-106X_mcRun2_asymptotic_preVFP_v11-v1/MINIAODSIM

/QCD_HT50to100_TuneCP5_PSWeights_13TeV-madgraph-pythia8/RunIISummer20UL17MiniAODv2-106X_mc2017_realistic_v9-v1/MINIAODSIM
/QCD_HT200to300_TuneCP5_PSWeights_13TeV-madgraph-pythia8/RunIISummer20UL17MiniAODv2-106X_mc2017_realistic_v9-v1/MINIAODSIM
/QCD_HT300to500_TuneCP5_PSWeights_13TeV-madgraph-pythia8/RunIISummer20UL17MiniAODv2-106X_mc2017_realistic_v9-v1/MINIAODSIM
/QCD_HT500to700_TuneCP5_PSWeights_13TeV-madgraph-pythia8/RunIISummer20UL17MiniAODv2-106X_mc2017_realistic_v9-v1/MINIAODSIM
/QCD_HT700to1000_TuneCP5_PSWeights_13TeV-madgraph-pythia8/RunIISummer20UL17MiniAODv2-106X_mc2017_realistic_v9-v1/MINIAODSIM

/QCD_HT1500to2000_TuneCP5_PSWeights_13TeV-madgraph-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v1/MINIAODSIM
/QCD_HT2000toInf_TuneCP5_PSWeights_13TeV-madgraph-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v1/MINIAODSIM
/QCD_HT200to300_TuneCP5_PSWeights_13TeV-madgraph-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v1/MINIAODSIM
/QCD_HT500to700_TuneCP5_PSWeights_13TeV-madgraph-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v1/MINIAODSIM
/QCD_HT50to100_TuneCP5_PSWeights_13TeV-madgraph-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v1/MINIAODSIM
/QCD_HT700to1000_TuneCP5_PSWeights_13TeV-madgraph-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v2/MINIAODSIM
```
3. Some GJets samples were added. I think this will complete UL16APV, but not UL16. Someone should double check:
```
/GJets_DR-0p4_HT-100To200_TuneCP5_13TeV-madgraphMLM-pythia8/RunIISummer20UL16MiniAODv2-106X_mcRun2_asymptotic_v17-v2/MINIAODSIM
/GJets_DR-0p4_HT-400To600_TuneCP5_13TeV-madgraphMLM-pythia8/RunIISummer20UL16MiniAODv2-106X_mcRun2_asymptotic_v17-v2/MINIAODSIM
/GJets_DR-0p4_HT-600ToInf_TuneCP5_13TeV-madgraphMLM-pythia8/RunIISummer20UL16MiniAODv2-106X_mcRun2_asymptotic_v17-v2/MINIAODSIM
/GJets_HT-40To100_TuneCP5_13TeV-madgraphMLM-pythia8/RunIISummer20UL16MiniAODv2-106X_mcRun2_asymptotic_v17-v1/MINIAODSIM

/GJets_DR-0p4_HT-100To200_TuneCP5_13TeV-madgraphMLM-pythia8/RunIISummer20UL16MiniAODAPVv2-106X_mcRun2_asymptotic_preVFP_v11-v2/MINIAODSIM
/GJets_DR-0p4_HT-200To400_TuneCP5_13TeV-madgraphMLM-pythia8/RunIISummer20UL16MiniAODAPVv2-106X_mcRun2_asymptotic_preVFP_v11-v2/MINIAODSIM
/GJets_DR-0p4_HT-400To600_TuneCP5_13TeV-madgraphMLM-pythia8/RunIISummer20UL16MiniAODAPVv2-106X_mcRun2_asymptotic_preVFP_v11-v2/MINIAODSIM
/GJets_DR-0p4_HT-600ToInf_TuneCP5_13TeV-madgraphMLM-pythia8/RunIISummer20UL16MiniAODAPVv2-106X_mcRun2_asymptotic_preVFP_v11-v2/MINIAODSIM
/GJets_HT-600ToInf_TuneCP5_13TeV-madgraphMLM-pythia8/RunIISummer20UL16MiniAODAPVv2-106X_mcRun2_asymptotic_preVFP_v11-v1/MINIAODSIM
```
4. Lots of samples have appeared for WJetsToQQ. Some are already in #594, but some samples are finished and are still missing from the PR.
5. The TTJets amcatnlo samples appear to be complete:
```
/TTJets_TuneCP5_13TeV-amcatnloFXFX-pythia8/RunIISummer20UL16MiniAOD-106X_mcRun2_asymptotic_v13-v1/MINIAODSIM
/TTJets_TuneCP5_13TeV-amcatnloFXFX-pythia8/RunIISummer20UL16MiniAODAPV-106X_mcRun2_asymptotic_preVFP_v8-v1/MINIAODSIM
/TTJets_TuneCP5_13TeV-amcatnloFXFX-pythia8/RunIISummer20UL18MiniAOD-106X_upgrade2018_realistic_v11_L1v1-v1/MINIAODSIM
```
It's MiniAOD and not MiniAODv2 though, so you may want to check if there is another sample in production.
6. Given all than I've pointed to which needs to be updated, it might be a good idea to check the other minor SM samples as well.

@JHiltbrand @cmadrid1 Can someone from your group update #594?

**Comment by JHiltbrand** [comment]
I put here a couple of event size metrics.

1. Our Stealth group has denoted that we would need the extra gen particles for the ttbar and signal samples.
- to give an idea of impact on event size, I did some tests with `saveMinimalGenParticles=False`, and find a O(20%) increase in event size when including the extra gen particles.

2. I also realize that the DeepFlavour prob variables were removed in February 2020 during a cleanup campaign. Awkwardly, the V17 ntuples we have been using all along have the DeepFlavour vars included and we have been using them as NN input variables without realizing their removal.
- To test this impact of adding back the five deep flavor variables, I did some local tests and find a O(10%) increase in event size when including the variables.

**Comment by JHiltbrand** [comment]
@aperloff 

For the GJets for 2016, are the DR 0p4 and non-DR-0p4 samples functionally equivalent ?
Is one preferred over the other ?

**Comment by kpedro88** [comment]
If you need DeepFlavour, it's fine to add it back. It was removed because nobody reported using it.

The GJets DR 0p4 and non-DR-0p4 samples are, to an extent, complementary: they have different gen-level phase space cuts. Which samples should be used depends on the particular situation.

**Comment by aperloff** [comment]
The Summer20UL16 sample below is now available, but wasn't included with the initial batch of V20 ntuples:
/GJets_HT-400To600_TuneCP5_13TeV-madgraphMLM-pythia8/RunIISummer20UL16MiniAODv2-106X_mcRun2_asymptotic_v17-v1/MINIAODSIM
