### ISSUE TITLE
Version Incompatibilty with Forked CMSSW for Run2_UL Branch

### ISSUE THREAD

**Issue by JHiltbrand** [TreeMaker/TreeMaker#599]
When running `TreeMaker` using the `Run2_UL` branch and specifying options that call `jetToolbox`, I encounter the following exception:

```
An exception of category 'ConfigFileReadError' occurred while
   [0] Processing the python configuration file named runMakeTreeFromMiniAOD_cfg.py
Exception Message:
 unknown python problem occurred.
ImportError: cannot import name _chsalgos_106X_UL16

At:
  /cvmfs/cms.cern.ch/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_6_29/python/PhysicsTools/NanoAOD/jets_cff.py(714): <module>
  /storage/local/data1/condor/execute/dir_6882/CMSSW_10_6_29/python/JMEAnalysis/JetToolbox/jetToolbox_cff.py(1309): jetToolbox
  /storage/local/data1/condor/execute/dir_6882/CMSSW_10_6_29/python/TreeMaker/TreeMaker/doZinvBkg.py(42): reclusterZinv
  /storage/local/data1/condor/execute/dir_6882/CMSSW_10_6_29/python/TreeMaker/TreeMaker/doZinvBkg.py(293): doZinvBkg
  /storage/local/data1/condor/execute/dir_6882/CMSSW_10_6_29/python/TreeMaker/TreeMaker/makeTreeFromMiniAOD_cff.py(1075): makeTreeFromMiniAOD
  runMakeTreeFromMiniAOD_cfg.py(84): <module>
```

I believe I have traced this to the `TreeMaker/AddJetAxis1_10620p1` branch, which pulls in its own version of `​RecoJets/​JetProducers` during `setup.sh`---the aforementioned branch based in an older 106X version. The missing name `_chsalgos_106X_UL16` trying to be imported only started appearing in the `PileupJetID_cfi.py` for >= CMSSW_10_6_26.

**Comment by kpedro88** [comment]
Just to check - did you set up a new area from scratch when you updated the CMSSW version? In general, merging a branch shouldn't bring in older versions of files that weren't modified.

**Comment by JHiltbrand** [comment]
Hmm, I had actually just re-setup with the latest version `setup.sh`; however, it appears I must not have completely reset my environment and was mixing versions. Running some more tests, the issue is resolved !
