### ISSUE TITLE
Adding PileUpJetID

### ISSUE THREAD

**Issue by kapsiak** [TreeMaker/TreeMaker#648]
Hello,

A recent presentation showed improved data/mc agreement using PileUp Jet ID.
These IDs are described on this twiki page by the Jet POG https://twiki.cern.ch/twiki/bin/viewauth/CMS/PileupJetID.

Would it be possible to add these to future NTuples.  

Thank you.

**Comment by kpedro88** [comment]
Resolved by https://github.com/TreeMaker/TreeMaker/pull/652
